backend:
  host: '127.0.0.1'
  port: 8000
  device: null
  cache_dir: '/home/hao/Workspace/neural-audio-sculptor/backend/.cache'
  music_dir: '/home/hao/Music/deemix Music'
  stylegan_checkpoints: '/home/hao/Documents/stylegan2_models'
frontend:
  host: localhost
  port: 5173
audio:
  sample_rate: 44100
  block_size: 512
  hop_length: 512
